# Generated by Django 5.1.7 on 2025-03-27 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='is_series',
            field=models.BooleanField(default=False, verbose_name='Is series'),
        ),
    ]
