# Generated by Django 5.1.7 on 2025-03-29 07:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_movie_is_series'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='num_of_seasons',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Number of seasons'),
        ),
        migrations.AddField(
            model_name='movie',
            name='series_last_year',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1900)], verbose_name='Series last year'),
        ),
    ]
