# Generated by Django 5.2 on 2025-04-16 09:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("movies", "0003_alter_country_options_alter_director_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="my_rating",
            field=models.FloatField(default=0.0, verbose_name="My rating"),
        ),
    ]
