# Generated by Django 5.2 on 2025-04-27 16:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_alter_country_options_alter_director_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MovieRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.FloatField(default=0.0, verbose_name='Movie rating')),
                ('review', models.TextField(blank=True, max_length=1000, verbose_name='Review')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.movie')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'MovieRating',
                'verbose_name_plural': 'MovieRatings',
                'ordering': ('user', 'movie'),
                'constraints': [models.UniqueConstraint(fields=('user', 'movie'), name='unique_rating')],
            },
        ),
    ]
