# Generated by Django 5.2 on 2025-05-09 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0010_alter_movierating_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='my_rating',
        ),
    ]
